import { useAppStore } from "@/store";
import { FileText, Printer, Warning } from "@phosphor-icons/react";

export default function ReportsTab() {
  const { scanResult, selectedLocation } = useAppStore();

  return (
    <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-800 p-8 min-h-[80vh] flex flex-col relative">
      <div className="flex items-center justify-between mb-8 border-b border-slate-100 dark:border-slate-800 pb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center">
            <FileText weight="duotone" className="w-5 h-5" />
          </div>
          <div>
            <h2 className="font-bold uppercase tracking-widest text-xs text-slate-400">Mission Summary</h2>
            <h1 className="text-xl font-black text-slate-900 dark:text-slate-100">Official Report</h1>
          </div>
        </div>
        <button 
          onClick={() => window.print()} 
          disabled={!scanResult}
          className="flex items-center gap-2 px-4 py-2 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-xl font-bold text-sm hover:bg-slate-200 dark:hover:bg-slate-700 disabled:opacity-50 transition-colors"
        >
          <Printer weight="bold" className="w-4 h-4" /> Print PDF
        </button>
      </div>

      {!scanResult ? (
        <div className="flex-1 flex flex-col items-center justify-center text-slate-400 gap-4">
          <Warning className="w-12 h-12 opacity-50" />
          <p className="font-medium text-sm">No active scan to generate a report. Select a target on the Dashboard.</p>
        </div>
      ) : (
        <div className="flex-1 overflow-y-auto print:overflow-visible">
          <div className="max-w-2xl mx-auto bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-8 print:border-none print:bg-white print:p-0">
            <div className="text-center mb-8 pb-8 border-b border-slate-200 dark:border-slate-700">
              <h2 className="text-2xl font-black tracking-tighter text-slate-900 dark:text-slate-100">KABAW TELEMETRY REPORT</h2>
              <div className="text-sm font-mono text-slate-500 mt-2">
                DATE: {new Date().toLocaleDateString()} | COORDS: {selectedLocation?.lat.toFixed(4)}, {selectedLocation?.lng.toFixed(4)}
              </div>
            </div>

            <div className="grid grid-cols-2 gap-6 mb-8">
              <div>
                <h3 className="font-bold text-xs uppercase tracking-widest text-slate-400 mb-2">Vegetation Index (NDVI)</h3>
                <div className="text-4xl font-black text-emerald-600">{scanResult.ndvi_score.toFixed(3)}</div>
              </div>
              <div>
                <h3 className="font-bold text-xs uppercase tracking-widest text-slate-400 mb-2">Moisture Index (NDWI)</h3>
                <div className="text-4xl font-black text-blue-600">{scanResult.ndwi_score.toFixed(3)}</div>
              </div>
            </div>

            <div className="space-y-6">
              <div>
                <h3 className="font-bold text-sm text-slate-900 dark:text-slate-100 mb-2">Automated Analysis</h3>
                <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                  Based on the spectral reflection data captured by the Sentinel-2 orbital sensor, the target area exhibits a Vegetation Index of {scanResult.ndvi_score.toFixed(3)}. 
                  {scanResult.ndvi_score > 0.5 ? " This suggests dense, healthy canopy cover with high photosynthetic activity." : " This indicates sparse or stressed vegetation, or non-agricultural land use."}
                  The Moisture Index of {scanResult.ndwi_score.toFixed(3)} 
                  {scanResult.ndwi_score > 0.1 ? " reveals significant surface water presence, potentially indicative of flooding or high soil saturation." : " indicates typical dry land conditions without significant standing surface water."}
                </p>
              </div>
            </div>
            
            <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-700 text-center">
              <div className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Generated by KABAW Land Monitoring System</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
